const test=require('node:test'),assert=require('node:assert/strict');
const {GanttExport:X}=require('../assets/export.js'),E=require('../assets/scheduler.js');
function fixture(){return {version:1,id:'export-demo',name:'Новый продукт',mode:'identity',sources:[],stages:[{id:'concept',label:'Концепция',color:'#ABCDEF',pool:'creative'}],settings:{start:'2031-06-02',holidays:['2031-06-03'],capacities:{creative:1},stageDurations:{concept:null},preserveSourceDates:true,overrides:{}},tasks:[{id:'C1',title:'Концепция',stage:'concept',workstream:'Brand',description:'INTERNAL_SECRET',acceptance:[],sourceRefs:[],dependsOn:[],duration:2,sourceStart:null,sourceEnd:null,notBefore:null,blocker:null,status:'planned',milestone:false,resourceGroup:null,aspro:null}]};}
function unzip(bytes){assert(bytes instanceof Uint8Array);const b=Buffer.from(bytes),out={};let i=0;while(b.readUInt32LE(i)===0x04034b50){const n=b.readUInt16LE(i+26),e=b.readUInt16LE(i+28),size=b.readUInt32LE(i+18),s=i+30+n+e;out[b.subarray(i+30,i+30+n).toString()]=b.subarray(s,s+size).toString();i=s+size;}return out;}
test('portable styled XLSX reflects stage palette, calendar and reserve without internal text',()=>{const p=fixture(),r=E.calculate(p),f=unzip(X.workbook(p,r));assert.equal(r.tasks[0].end,'2031-06-04');assert(f['xl/styles.xml'].includes('FFABCDEF'));assert(f['xl/worksheets/sheet3.xml'].includes('2031-06-03'));assert(!Object.values(f).some(v=>v.includes('INTERNAL_SECRET')||v.includes('AffArts')));assert(f['xl/worksheets/sheet2.xml'].includes('Полный резерв'));assert(f['xl/workbook.xml'].includes('Календарь'));assert(!Object.values(f).some(v=>/<f(?:\s|>)/.test(v)));});
test('unknown work remains blank and repeated exports do not accumulate stage styles',()=>{const p=fixture();p.tasks[0].duration=null;const r=E.calculate(p),a=unzip(X.workbook(p,r)),b=unzip(X.workbook(p,r));assert.equal(a['xl/styles.xml'],b['xl/styles.xml']);assert(a['xl/worksheets/sheet2.xml'].includes('Не рассчитано'));assert(a['xl/worksheets/sheet1.xml'].includes('Полное завершение не определено'));});
test('hourly XLSX retains effort, people and RF holiday/short-day calendar',()=>{
 const p=require('../examples/hourly-project.json'),r=E.calculate(p),f=unzip(X.workbook(p,r)),cal=f['xl/worksheets/sheet4.xml'];
 assert(f['xl/worksheets/sheet2.xml'].includes('Смета, ч.'));assert(f['xl/worksheets/sheet2.xml'].includes('По часам'));assert(f['xl/worksheets/sheet3.xml'].includes('РФ 2026'));assert(f['xl/worksheets/sheet3.xml'].includes('Число потоков'));assert(f['xl/worksheets/sheet3.xml'].includes('hoursPerDay'));
 const row3=cal.match(/<row r="3"[^>]*>(.*?)<\/row>/)[1],row4=cal.match(/<row r="4"[^>]*>(.*?)<\/row>/)[1];
 assert(row3.includes('Сокращённый день'));assert.match(row3,/<c r="E3"[^>]*><v>7<\/v>/);assert.match(row4,/<c r="C4"[^>]*><v>0<\/v>/);assert.match(row4,/<c r="E4"[^>]*><v>0<\/v>/);
});
