'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const P=require('../scripts/pipeline.cjs');
function fixture(){const p=P.init('website','synthetic-project','Учебный проект');p.sources=[{id:'brief',title:'Пример ТЗ',text:'Нужна главная страница.'}];p.settings.start='2027-03-01';p.settings.capacities.design=1;p.tasks=[{id:'T1',title:'Макет главной',stage:'design',workstream:'Главная',description:'Создать макет из исходного ТЗ',acceptance:['Макет согласован'],sourceRefs:[{sourceId:'brief',quote:'Нужна главная страница.'}],dependsOn:[],duration:2,sourceStart:null,sourceEnd:null,notBefore:null,blocker:null,status:'planned',milestone:false,resourceGroup:null,aspro:null}];return p;}
const config={stageField:'project_stage_id',bindings:{design:{projectId:10,stageId:20}},taskUrlTemplate:'https://example.aspro.cloud/tasks/{id}'};
function snap(tasks=[]){return{complete:true,projects:[{id:10}],stages:[{id:20,project_id:10}],tasks};}
function remote(p){return{id:900,...P.asproPlan(p,config,snap()).operations[0].data};}
test('mode initialization does not carry historical estimates, dates, accounts or tasks',()=>{for(const m of ['website','identity','mobile']){const p=P.init(m,'sample','Пример');assert.equal(p.mode,m);assert.equal(p.tasks.length,0);assert.equal(p.settings.start,null);assert.ok(Object.values(p.settings.capacities).every(x=>x===null));assert.ok(!JSON.stringify(p).includes('AffArts'));}});
test('quotes must exist; unsupported work is explicitly proposed',()=>{const p=fixture();assert.deepEqual(P.validateContext(p),[]);p.tasks[0].sourceRefs[0].quote='Invented';assert.ok(P.validateContext(p).some(x=>x.includes('quote')));p.tasks[0].sourceRefs=[];assert.ok(P.validateContext(p).length);p.tasks[0].title='Предложение: проверка';assert.deepEqual(P.validateContext(p),[]);});
test('plan is idempotent by stable reference and has no destructive or schedule writes',()=>{const p=fixture(),first=P.asproPlan(p,config,snap());assert.equal(first.operations[0].action,'create');const data=first.operations[0].data;assert.equal(data.parent_id,0);for(const key of ['responsible_id','deadline','plan_start_date','time_estimate','status'])assert.ok(!(key in data));const second=P.asproPlan(p,config,snap([remote(p)]));assert.equal(second.operations[0].action,'noop');});
test('same-name collisions, duplicate references and wrong-scope records block creation',()=>{const p=fixture(),r=remote(p);assert.throws(()=>P.asproPlan(p,config,snap([{...r,ref:'',ref_id:''}])),/same-name/);assert.throws(()=>P.asproPlan(p,config,snap([r,{...r,id:901}])),/ambiguous/);assert.throws(()=>P.asproPlan(p,config,snap([{...r,model_id:99}])),/another project/);assert.throws(()=>P.asproPlan(p,config,{...snap(),complete:false}),/Complete/);assert.throws(()=>P.asproPlan(p,config,{...snap(),stages:[{id:20,project_id:11}]}),/belong/);});
test('PM gate requires verified bindings and expires on composition change',()=>{const p=fixture();assert.throws(()=>P.approval(p,'PM'),/linked/);const linked=P.reconcile(p,config,snap([remote(p)])),a=P.approval(linked,'Test PM');assert.ok(P.approved(linked,a));linked.settings.start='2027-03-02';assert.ok(P.approved(linked,a));linked.tasks[0].title+=' changed';assert.ok(!P.approved(linked,a));assert.throws(()=>P.build(linked,a),/missing or stale/);});
test('public projection removes descriptions, sources, extra fields and unsafe links',()=>{const p=fixture();p.secret='DO_NOT_PUBLISH';p.sources[0].text+=' INTERNAL_TEXT';p.tasks[0].description='INTERNAL_DESCRIPTION';p.tasks[0].aspro={id:1,projectId:10,stageId:20,url:'https://example.org/task?api_key=SECRET'};p.settings.secret='CONFIG_SECRET';const out=JSON.stringify(P.publicProject(p));for(const marker of ['DO_NOT_PUBLISH','INTERNAL_TEXT','INTERNAL_DESCRIPTION','CONFIG_SECRET','api_key'])assert.ok(!out.includes(marker));});
test('standalone approved HTML embeds valid scripts, preserves controls and escapes script injection',()=>{const p=fixture();p.name='Test </script><img src=x onerror=alert(1)>';const linked=P.reconcile(p,config,snap([remote(p)])),html=P.build(linked,P.approval(linked,'Fixture PM'));assert.ok(!html.includes('<img src=x'));assert.ok(!/__PROJECT__|__APP__|__ENGINE__/.test(html));for(const code of [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]))assert.doesNotThrow(()=>new vm.Script(code));assert.ok(html.includes('refreshSource'));assert.ok(html.includes('showCritical'));assert.ok(html.includes('exportXlsx'));assert.throws(()=>P.build(linked,null),/PM approval/);assert.ok(P.build(linked,null,{preview:true}).includes('ЧЕРНОВИК'));});

test('missing bound remote task never becomes an automatic duplicate',()=>{const p=fixture();p.tasks[0].aspro={id:999,projectId:10,stageId:20,url:null};assert.throws(()=>P.asproPlan(p,config,snap()),/bound remote task missing/);});

test('read-back imports portal calendar dates and status without timezone shifts or invented start',()=>{const p=fixture(),r={...remote(p),plan_start_date:'2027-03-03 09:00:00',deadline:'2027-03-04 18:00:00',status:5},linked=P.reconcile(p,config,snap([r]));assert.equal(linked.tasks[0].sourceStart,'2027-03-03');assert.equal(linked.tasks[0].sourceEnd,'2027-03-04');assert.equal(linked.tasks[0].status,'completed');r.plan_start_date='0000-00-00 00:00:00';assert.equal(P.reconcile(p,config,snap([r])).tasks[0].sourceStart,null);r.deadline='bad';assert.throws(()=>P.reconcile(p,config,snap([r])),/Invalid Aspro date/);});
