// A small DOM fixture exercises production UI handlers with the real engine.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const E=require('../assets/scheduler.js'),{GanttExport}=require('../assets/export.js');
function fixture(){
 const nodes=new Map(),virtual=[],events={},blobs=[],attrs=s=>Object.fromEntries([...s.matchAll(/([\w-]+)="([^"]*)"/g)].map(x=>[x[1],x[2]]));
 class El{constructor(id){this.id=id;this.value='';this.checked=false;this.dataset={};this.style={setProperty(){}};this.cache=new Map();this.scrollLeft=0;this.scrollTop=0;this.scrollHeight=1000;this.classList={toggle(){}};this.textContent='';}set innerHTML(s){this.html=s;this.cache.clear();parse(s);}get innerHTML(){return this.html||'';}setAttribute(k,v){this[k]=v;}getBoundingClientRect(){return this.rect||{left:0,top:0,width:1500,height:1000};}setPointerCapture(){}releasePointerCapture(){}scrollIntoView(){}focus(){}select(){}click(){return this.onclick?.();}querySelectorAll(selector){if(this.cache.has(selector))return this.cache.get(selector);const key=selector.includes('data-group-bar')?'group-bar':selector.includes('data-group')?'group':selector.includes('data-task')?'task':null;if(!key)return [];const found=[...this.innerHTML.matchAll(new RegExp('<button[^>]*data-'+key+'="([^"]*)"[^>]*>','g'))].filter(m=>!selector.startsWith('.bar')||/class="bar\b/.test(m[0])).map((m,i)=>{const n=new El(),a=attrs(m[0]);n.dataset[key==='group-bar'?'groupBar':key]=m[1];n.rect={left:570+Number(a.style?.match(/left:([\d.]+)/)?.[1]||0),top:100+i*45,width:Number(a.style?.match(/width:([\d.]+)/)?.[1]||25),height:23};return n;});this.cache.set(selector,found);return found;}}
 function parse(s){for(const m of s.matchAll(/<[a-z]+[^>]*>/g)){const a=attrs(m[0]);if(a.id){const n=new El(a.id);n.value=a.value||'';n.checked=/\bchecked\b/.test(m[0]);nodes.set(a.id,n);}for(const [key,data] of [['pool','data-pool'],['stage','data-stage']])if(a[data]){const n=new El();n.dataset[key]=a[data];n.value=a.value||'';const index=virtual.findIndex(x=>x.dataset[key]===a[data]);if(index>=0)virtual.splice(index,1);virtual.push(n);}}}
 parse(fs.readFileSync(__dirname+'/../assets/shell.html','utf8'));nodes.get('zoom').value='26';nodes.get('view').value='stages';
 const task=(id,stage,dependsOn=[])=>({id,title:id,stage,workstream:'Страница',description:'',acceptance:[],sourceRefs:[],dependsOn,duration:1,sourceStart:null,sourceEnd:null,notBefore:null,blocker:null,status:'planned',milestone:false,resourceGroup:null,aspro:null});
 const project={version:1,id:'ui-demo',name:'План продукта',mode:'website',sources:[],stages:[{id:'design',label:'Дизайн',pool:'design',color:'#47765C'},{id:'frontend',label:'Фронтенд',pool:'frontend',color:'#52788E'}],settings:{start:'2030-04-01',holidays:[],capacities:{design:1,frontend:1},stageDurations:{design:null,frontend:null},preserveSourceDates:true,overrides:{}},tasks:[task('D','design'),task('F','frontend',['D'])]};
 const document={getElementById:id=>nodes.get(id),documentElement:{},querySelectorAll:s=>virtual.filter(n=>s.includes('data-pool')&&n.dataset.pool||s.includes('data-stage')&&n.dataset.stage),createElement:()=>new El()};
 class URLs extends URL{static createObjectURL(b){blobs.push(b);return 'blob:fixture';}static revokeObjectURL(){}}
 const box={document,PROJECT:project,GanttEngine:E,GanttExport,URL:URLs,Blob,TextEncoder,Date,console,location:{href:'https://planner.test/',hash:''},navigator:{},localStorage:{getItem:()=>null,setItem(){}},getComputedStyle:()=>({getPropertyValue:()=>570}),setTimeout:fn=>fn(),confirm:()=>true,addEventListener:(name,fn)=>events[name]=fn};box.window=box;vm.runInNewContext(fs.readFileSync(__dirname+'/../assets/app.js','utf8'),box);return {nodes,events,box,blobs};
}
test('full UI binds presets, groups, links and native XLSX export to current scenario',async()=>{const {nodes,box,blobs}=fixture();assert.equal(nodes.get('error').textContent,'');assert.equal(box.ganttApp.current.tasks.length,2);assert(nodes.get('cards').innerHTML.includes('2030'));assert(nodes.get('dependencyLayer').innerHTML.includes('D → F'));nodes.get('presetFront').click();assert.equal(box.ganttApp.settings.capacities.frontend,2);nodes.get('presetBase').click();assert.equal(box.ganttApp.settings.capacities.frontend,1);nodes.get('view').value='workstream';nodes.get('view').onchange();assert(nodes.get('chart').innerHTML.includes('Страница'));nodes.get('collapse').click();assert.equal(box.ganttApp.current.tasks.length,2);nodes.get('exportXlsx').click();const b=new Uint8Array(await blobs.at(-1).arrayBuffer());assert.deepEqual([...b.slice(0,2)],[80,75]);assert.equal(nodes.get('refreshSource').disabled,true);});
test('pointer preview stays temporary; release commits and Escape/undo preserve previous plan',()=>{const {nodes,events,box}=fixture(),bars=()=>nodes.get('chart').querySelectorAll('.bar[data-task]');let bar=bars().find(b=>b.dataset.task==='F');bar.onpointerdown({button:0,pointerId:1,clientX:100});events.pointermove({pointerId:1,clientX:126,preventDefault(){}});assert.equal(box.ganttApp.settings.overrides.F,undefined);events.pointerup({pointerId:1});assert.equal(box.ganttApp.settings.overrides.F.moveTo,'2030-04-03');nodes.get('undoMove').click();assert.equal(box.ganttApp.settings.overrides.F,undefined);bar=bars().find(b=>b.dataset.task==='F');bar.onpointerdown({button:0,pointerId:2,clientX:100});events.pointermove({pointerId:2,clientX:180,preventDefault(){}});events.keydown({key:'Escape',preventDefault(){}});assert.equal(box.ganttApp.settings.overrides.F,undefined);});
