const test=require('node:test'),assert=require('node:assert/strict');
const UI=require('../assets/app.js'),E=require('../assets/scheduler.js');
function task(id,extra={}){return {id,title:id,stage:'design',workstream:'Page',description:'',acceptance:[],sourceRefs:[],dependsOn:[],duration:2,sourceStart:null,sourceEnd:null,notBefore:null,blocker:null,status:'planned',milestone:false,resourceGroup:null,aspro:null,...extra};}
function fixture(){return {version:1,id:'demo',name:'Demo',mode:'website',sources:[],stages:[{id:'design',label:'Дизайн',color:'#47765c',pool:'design'}],settings:{start:'2030-04-01',holidays:[],capacities:{design:1},stageDurations:{design:null},preserveSourceDates:true,overrides:{}},tasks:[task('T1'),task('T2',{dependsOn:['T1']})]};}
test('settings share/import retain scope and reject another project without mutation',()=>{const p=fixture(),before=JSON.stringify(p),payload=UI.envelope(p,{...p.settings,overrides:{T1:{moveTo:'2030-04-08'}}});assert.equal(UI.readEnvelope(p,payload,E).overrides.T1.moveTo,'2030-04-08');assert.throws(()=>UI.readEnvelope({...p,id:'other'},payload,E),/другого проекта/);assert.equal(JSON.stringify(p),before);});
test('drag preserves duration and moves the whole resource group without writing source',()=>{const p=fixture();p.tasks=[task('T1',{resourceGroup:'one'}),task('T2',{resourceGroup:'one'})];const t=E.calculate(p).tasks[0],o=UI.moves(p,p.settings,t,'2030-04-08');assert.deepEqual(o.T1,{moveTo:'2030-04-08',duration:2});assert.deepEqual(o.T2,o.T1);assert.deepEqual(p.settings.overrides,{});const r=E.calculate(p,{overrides:o});assert.equal(r.tasks[0].start,'2030-04-08');assert.equal(r.tasks[1].start,r.tasks[0].start);});
test('refresh keeps matching overrides, adds unestimated tasks and leaves stale source unchanged',()=>{const p=fixture(),next=structuredClone(p);next.tasks.push(task('T3',{duration:null}));const settings={...p.settings,overrides:{T1:{moveTo:'2030-04-08'},removed:{ready:'2030-04-01'}}};const loaded=UI.refreshed(p,next,settings,E);assert(loaded.settings.overrides.T1);assert(!loaded.settings.overrides.removed);assert.equal(E.calculate(loaded.project,loaded.settings).tasks.find(t=>t.id==='T3').start,null);assert.equal(p.tasks.length,2);assert.throws(()=>UI.refreshed(p,{...next,id:'other'},settings,E),/другой проект/);});
test('sync endpoint refuses third-party and offline access',()=>{const p=fixture();p.sync={url:'/api/aspro/snapshot'};assert.equal(UI.syncEndpoint(p,'https://planner.test/app'),'https://planner.test/api/aspro/snapshot');assert.equal(UI.syncEndpoint(p,'file:///tmp/app.html'),null);p.sync.url='https://other.test/api/aspro/snapshot';assert.equal(UI.syncEndpoint(p,'https://planner.test/'),null);p.sync.url='/api/anything';assert.equal(UI.syncEndpoint(p,'https://planner.test/'),null);});
test('refresh never removes the draft label from an unapproved preview',()=>{const p=fixture();p.name='ЧЕРНОВИК · Demo';const next=structuredClone(p);next.name='Updated';const result=UI.refreshed(p,next,p.settings,E);assert.equal(result.project.name,'ЧЕРНОВИК · Updated');assert.equal(next.name,'Updated');});
